version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    cooldown:
      default-days: 14

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    cooldown:
      default-days: 14

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    cooldown:
      default-days: 14

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    cooldown:
      default-days: 14
